package com.mahait.gov.in.nps.model;

import java.time.LocalDateTime;

import lombok.Data;

@Data
public class FormS1DetailsModel {

	private Long formS1Id;
	private String sevarthId;
	private String dcpsId;
	private String designation;
	private String title;
	private String empName;
	private String empFirstName;
	private String empMiddleName;
	private String empLastName;
	private String fatherNameFirst;
	private String fatherNameMiddle;
	private String fatherNameLast;
	private String motherNameFirst;
	private String empDob;
	private String gender;
	private String dtoCode;
	private String ddoCode;
	private String panNo;
	private String aadharNo;
	private String presentAddressFlatNo;
	private String presentAddressBuilding;
	private String presentAddressTaluka;
	private String presentAddressLandmark;
	private String presentAddressDistrict;
	private String presentAddressState;
	private String presentAddressCountry;
	private String presentAddressPincode;
	private String permanentAddressFlatNo;
	private String permanentAddressBuilding;
	private String permanentAddressTaluka;
	private String permanentAddressLandmark;
	private String permanentAddressDistrict;
	private String permanentAddressState;
	private String permanentAddressCountry;
	private String permanentAddressPincode;
	private String phoneNo;
	private String mobileNo;
	private String emailId;
	private String smsSubFlag;
	private String emailSubFlag;
	private String hindiSubFlag;
	private String empDoj;
	private String empDor;
	private String empClass;
	private String empDept;
	private String empMinistry;
	private String empDdo;
	private String payScale;
	private String basicSalary;
	private String ppan;
	private String bankDetailsFlag;
	private String bankDetailsType;
	private String bankAccountNo;
	private String bankName;
	private String bankBranch;
	private String bankAddress;
	private String bankState;
	private String bankCountry;
	private String bankPin;
	private String empNumberNominee;
	private String nomineeName1;
	private String nomineeDob1;
	private String nomineeRelation1;
	private String nomineePercentShare1;
	private String nomineeGuardianName1;
	private String nomineeRenderCondition1;
	private String nomineeName2;
	private String nomineeDob2;
	private String nomineeRelation2;
	private String nomineePercentShare2;
	private String nomineeGuardianName2;
	private String nomineeRenderCondition2;
	private String nomineeName3;
	private String nomineeDob3;
	private String nomineeRelation3;
	private String nomineePercentShare3;
	private String nomineeGuardianName3;
	private String nomineeRenderCondition3;
	private String pranNo;
	private LocalDateTime createdDate;
	private String bankIfscCode;
	private String empMaritalStatus;
	private String ddoRegNo;
	private String ackno;
	private String fileVerifyStatus;
	private Integer nsdlStatus;
	private String batchId;
	private String photoAttachmentName;
	private String signAttachmentName;
	private String imagesLocationPath;
	private Integer pranStatus;
	private String nomineeAddress1;
	private String nomineeAddress2;
	private String nomineeAddress3;
	private Integer statusFlag;

}
