
package com.mahait.gov.in.nps.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.io.FileInputStream;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.BindingProvider;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-15T19:54:17.915+05:30
 * Generated source version: 3.0.1
 * 
 */
public final class STPWebServicePOJO_STPWebServicePOJOPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.core.stp.cra.com/", "STPWebServicePOJOService");

    private STPWebServicePOJO_STPWebServicePOJOPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = STPWebServicePOJOService.WSDL_LOCATION;
      /*  if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }*/
      
        
 
        STPWebServicePOJOService ss = new STPWebServicePOJOService(wsdlURL, SERVICE_NAME);
        STPWebServicePOJO port = ss.getSTPWebServicePOJOPort();  
        BindingProvider bindingProvider = (BindingProvider) port;
        bindingProvider.getRequestContext().put(
        	      BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
        	      "https://www.npscan-cra.com/STPWeb/STPWebServicePOJOPort?wsdl");
        
       {
        	 System.out.println("Invoking performFileUpload...");
             java.util.List<byte[]> _performFileUpload_arg0 = new java.util.ArrayList<byte[]>();
              String ddoCode="3107602";
            // String zipFileName = "" +
             		String zipFileName = "D:/Test/"+ddoCode+".zip";
             PerformFileUpload fileUpload = new PerformFileUpload();
             byte[] fileByte;
             File zipFile = new File(zipFileName);

             FileInputStream fis = new FileInputStream(zipFileName);
           
             fileByte = new byte[(int) zipFile.length()];
             fis.read(fileByte);
             
             System.out.println(fileByte.toString());
             
             
             byte[][] _performFileUpload_arg0Val1 = new byte[3][0];
             _performFileUpload_arg0Val1[0] = "112563230".getBytes();
             _performFileUpload_arg0Val1[1] = "Upload SubscriberContribution-DSC".getBytes();
             _performFileUpload_arg0Val1[2] = fileByte; // zip file byte
             _performFileUpload_arg0.add(_performFileUpload_arg0Val1[0]);
             _performFileUpload_arg0.add(_performFileUpload_arg0Val1[1]);
             _performFileUpload_arg0.add(_performFileUpload_arg0Val1[2]);
             java.lang.String _performFileUpload__return = port.performFileUpload(_performFileUpload_arg0);
             System.out.println("performFileUpload.result=" + _performFileUpload__return);
             //System.out.println("performFileUpload.result=" + _performFileUpload__return);
            // System.out.println("performFileUpload.result=" + _performFileUpload__return);

        }
        /*{
        System.out.println("Invoking performFileDownload...");
        java.util.List<byte[]> _performFileDownload_arg0 = new java.util.ArrayList<byte[]>();
        byte[] _performFileDownload_arg0Val1 = new byte[] {};
        _performFileDownload_arg0.add(_performFileDownload_arg0Val1);
        java.util.List<byte[]> _performFileDownload__return = port.performFileDownload(_performFileDownload_arg0);
        System.out.println("performFileDownload.result=" + _performFileDownload__return);


        }*/
        {
       // System.out.println("Invoking performStatusInquiry...");
       // java.util.List<byte[]> _performStatusInquiry_arg0 = new java.util.ArrayList<byte[]>();
       // byte[] _performStatusInquiry_arg0Val1 = new byte[] {};
       // _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1);
       // java.lang.String _performStatusInquiry__return = port.performStatusInquiry(_performStatusInquiry_arg0);
        //System.out.println("performStatusInquiry.result=" + _performStatusInquiry__return);

        	/*System.out.println("Invoking perform status enquiry...");
            java.util.List<byte[]> _performStatusInquiry_arg0 = new java.util.ArrayList<byte[]>();
            
            String zipFileName = "E:/sign/+2202201607003+".sig";
            PerformFileUpload fileUpload = new PerformFileUpload();
            byte[] fileByte;
            File zipFile = new File(zipFileName);

            FileInputStream fis = new FileInputStream(zipFileName);

            fileByte = new byte[(int) zipFile.length()];
            fis.read(fileByte);
            
            System.out.println(fileByte.toString());

        	byte[][] _performStatusInquiry_arg0Val1 = new byte[5][0];
             _performStatusInquiry_arg0Val1[0] = "1013027630".getBytes();
             _performStatusInquiry_arg0Val1[1] = "1048006".getBytes();
             _performStatusInquiry_arg0Val1[2] = "10078897".getBytes(); // zip file byte
             _performStatusInquiry_arg0Val1[3] = fileByte; // zip file byte
             _performStatusInquiry_arg0Val1[4] = "File Status-SubscriberContribution".getBytes();; // zip file byte
             
             _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1[0]);
             _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1[1]);
             _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1[2]);
             _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1[3]);
             _performStatusInquiry_arg0.add(_performStatusInquiry_arg0Val1[4]);
             java.lang.String _performStatusInquiry__return = port.performStatusInquiry(_performStatusInquiry_arg0);
             System.out.println("performStatusInquiry.result=" + _performStatusInquiry__return);*/
             
             
        }

         
    }

}
