
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.mahait.gov.in.nps.webservice;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-15T19:54:18.032+05:30
 * Generated source version: 3.0.1
 * 
 */

/*@javax.jws.WebService(
                      serviceName = "STPWebServicePOJOService",
                      portName = "STPWebServicePOJOPort",
                      targetNamespace = "http://webservice.core.stp.cra.com/",
                      wsdlLocation = "/home/contribution/STPWebServicePOJOPort.wsdl",
                      endpointInterface = "com.mahait.gov.in.controller.nsdl.STPWebServicePOJO")*/


                      
public class STPWebServicePOJOPortImpl implements STPWebServicePOJO {
	
	
	

    private static final Logger LOG = Logger.getLogger(STPWebServicePOJOPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cra.stp.core.webservice.STPWebServicePOJO#performFileUpload(java.util.List<byte[]>  arg0 )*
     */
    public java.lang.String performFileUpload(java.util.List<byte[]> arg0) { 
        LOG.info("Executing operation performFileUpload");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return309751701";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cra.stp.core.webservice.STPWebServicePOJO#performFileDownload(java.util.List<byte[]>  arg0 )*
     */
    public java.util.List<byte[]> performFileDownload(java.util.List<byte[]> arg0) { 
        LOG.info("Executing operation performFileDownload");
        System.out.println(arg0);
        try {
            java.util.List<byte[]> _return = new java.util.ArrayList<byte[]>();
            byte[] _returnVal1 = new byte[] {};
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cra.stp.core.webservice.STPWebServicePOJO#performStatusInquiry(java.util.List<byte[]>  arg0 )*
     */
    public java.lang.String performStatusInquiry(java.util.List<byte[]> arg0) { 
        LOG.info("Executing operation performStatusInquiry");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-384851704";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
