package com.mahait.gov.in.nps.webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-15T19:54:18.060+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://webservice.core.stp.cra.com/", name = "STPWebServicePOJO")
@XmlSeeAlso({ObjectFactory.class})
public interface STPWebServicePOJO {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "performFileUpload", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformFileUpload")
    @WebMethod(action = "urn:PerformFileUpload")
    @ResponseWrapper(localName = "performFileUploadResponse", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformFileUploadResponse")
    public java.lang.String performFileUpload(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<byte[]> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "performFileDownload", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformFileDownload")
    @WebMethod(action = "urn:performFileDownload")
    @ResponseWrapper(localName = "performFileDownloadResponse", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformFileDownloadResponse")
    public java.util.List<byte[]> performFileDownload(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<byte[]> arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "performStatusInquiry", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformStatusInquiry")
    @WebMethod(action = "urn:PerformStatusInquiry")
    @ResponseWrapper(localName = "performStatusInquiryResponse", targetNamespace = "http://webservice.core.stp.cra.com/", className = "com.mahait.gov.in.controller.nsdl.PerformStatusInquiryResponse")
    public java.lang.String performStatusInquiry(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<byte[]> arg0
    );
}
