package com.mahait.gov.in.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

@Data
@Entity
@Table(name = "frm_sub_postid_mpg")
public class SubjectPostMpg {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Assuming ID is generated by the database
	@Column(name = "POST_ID") // Maps to column name "POST_ID"
	private Long postId;

	@Column(name = "SUBJECT_NAME", nullable = false, length = 100) // Maps to column name "SUBJECT_NAME"
	private String subjectName;

}
